name: Github profile indexer CI

on: [push, pull_request]

jobs:
  client-frontend:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: client

    steps:
      - name: Check repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.1'

      - name: Install Node.js dependencies
        run: yarn

      - name: Run Unit Tests
        run: yarn test:unit

      - name: Build
        run: yarn build

  api-backend:
  
    runs-on: ubuntu-latest

    steps:
      - name: Check repository
        uses: actions/checkout@v1

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
          
      - name: Create database
        run: docker-compose run github-profile-indexer-api rake db:create

      - name: Run migrations
        run: docker-compose run github-profile-indexer-api rake db:migrate
